name: Daily Newsletter

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST
    - cron: '0 21 * * *'  # 4 PM EST
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("httr2", "digest", "lubridate", "tidyRSS", "googlesheets4", "emayili", "markdown", "curl", "tidyverse"))'

      - name: Cache guids.csv
        id: cache-guids
        uses: actions/cache@v3
        with:
          path: guids.csv
          key: guids-${{ runner.os }}--${{ github.run_id }}
          restore-keys: |
            guids-${{ runner.os }}-

      - name: Check if guids.csv exists in cache
        shell: bash
        run: |
          if [[ steps.cache-guids.outputs.cache-hit == 'true' ]]; then
            echo "GUIDs file found in cache."
            echo "guids_found=true" >> $GITHUB_ENV
          else:
            echo "No GUIDs file found in cache."
            echo "guids_found=false" >> $GITHUB_ENV
          fi

      - name: Execute R Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RSS_SHEET_URL: ${{ secrets.RSS_SHEET_URL }}
          RSS_SHEET_NAME_SECTIONS: ${{ secrets.RSS_SHEET_NAME_SECTIONS || 'Sections' }}
          RSS_SHEET_NAME_FEEDS: ${{ secrets.RSS_SHEET_NAME_FEEDS || 'Feeds' }}
        run: Rscript ai_newsletter_script.R

      - name: Check if guids.csv exists after R script
        run: |
          if (Test-Path -Path "guids.csv") {
            echo "guids.csv exists after R script"
          } else {
            echo "guids.csv does NOT exist after R script"
          }

      - name: Show content of guids.csv after R script
        run: |
          if (Test-Path -Path "guids.csv") {
            Get-Content "guids.csv"
          } else {
            echo "guids.csv does not exist"
          }

      # The cache will be updated automatically if guids.csv is modified

      - name: Write Newsletter to workflow summary
        shell: bash
        run: |
          cat newsletter.md >> $GITHUB_STEP_SUMMARY
