name: Daily Newsletter

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST
    - cron: '0 21 * * *'  # 4 PM EST
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("httr2", "digest", "lubridate", "tidyRSS", "googlesheets4", "emayili", "markdown", "curl"))'

      - name: Log Cache Key Before Restore
        run: echo "Cache key before restore: ${{ runner.os }}-guids"

      - name: Cache GUIDs (Restore)
        id: cache-guids
        uses: actions/cache@v4
        if: always() # Attempt to restore even on failure for robustness 
        with:
          path: guids.csv
          key: ${{ runner.os }}-guids
          restore-keys: |
            ${{ runner.os }}-guids

      - name: Execute R Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RSS_SHEET_URL: ${{ secrets.RSS_SHEET_URL }}
          RSS_SHEET_NAME_SECTIONS: ${{ secrets.RSS_SHEET_NAME_SECTIONS || 'Sections' }}
          RSS_SHEET_NAME_FEEDS: ${{ secrets.RSS_SHEET_NAME_FEEDS || 'Feeds' }}
        run: Rscript ai_newsletter_script.R

      - name: Log Cache Key Before Save
        run: echo "Cache key before save: ${{ runner.os }}-guids"

      - name: Save Cache (GUIDs)
        uses: actions/cache@v4
        if: success() # Only save cache if R script succeeded
        with:
          path: guids.csv
          key: ${{ runner.os }}-guids

      - name: Write Newsletter to workflow summary
        shell: bash
        run: |
            cat newsletter.md >> $GITHUB_STEP_SUMMARY