name: Daily Newsletter

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST
    - cron: '0 21 * * *'  # 4 PM EST
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to allow git add/commit

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("httr2", "digest", "lubridate", "tidyRSS", "googlesheets4", "emayili", "markdown", "curl", "tidyverse"))'

      - name: Check if guids.csv exists in repository
        shell: bash
        run: |
          if [[ -f "guids.csv" ]]; then
            echo "GUIDs file found in repository."
            echo "guids_found=true" >> $GITHUB_ENV
          else:
            echo "No GUIDs file found in repository."
            echo "guids_found=false" >> $GITHUB_ENV
          fi

      - name: Execute R Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RSS_SHEET_URL: ${{ secrets.RSS_SHEET_URL }}
          RSS_SHEET_NAME_SECTIONS: ${{ secrets.RSS_SHEET_NAME_SECTIONS || 'Sections' }}
          RSS_SHEET_NAME_FEEDS: ${{ secrets.RSS_SHEET_NAME_FEEDS || 'Feeds' }}
        run: Rscript ai_newsletter_script.R

      - name: Check if guids.csv exists after R script
        run: |
          if (Test-Path -Path "guids.csv") {
            echo "guids.csv exists after R script"
          } else {
            echo "guids.csv does NOT exist after R script"
          }

      - name: Show content of guids.csv after R script
        run: |
          if (Test-Path -Path "guids.csv") {
            Get-Content "guids.csv"
          } else {
            echo "guids.csv does not exist"
          }

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name 'GitHub Actions Bot' # Set the name of the committer
          git config --global user.email 'actions@github.com' # Set the email of the committer
          git add guids.csv
          git commit -m "Update guids.csv" || echo "No changes to commit"
          git push

      - name: Write Newsletter to workflow summary
        shell: bash
        run: |
          cat newsletter.md >> $GITHUB_STEP_SUMMARY
