name: Daily Newsletter

on:
  schedule:
    - cron: '0 11 * * *'  # Runs daily at 11:00 AM UTC (adjust as needed)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages(c("httr2", "blastula", "digest", "lubridate", "tidyRSS", "googlesheets4"))

      - name: Cache GUIDs
        id: cache-guids
        uses: actions/cache@v3
        with:
          path: guids.csv
          key: ${{ runner.os }}-guids-${{ hashFiles('newsletter_script.R') }}
          restore-keys: |
            ${{ runner.os }}-guids-

      - name: Execute R Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RSS_SHEET_URL: ${{ secrets.RSS_SHEET_URL }}
          RSS_SHEET_NAME_SECTIONS: ${{ secrets.RSS_SHEET_NAME_SECTIONS || 'Sections' }}
          RSS_SHEET_NAME_FEEDS: ${{ secrets.RSS_SHEET_NAME_FEEDS || 'Feeds' }}
          RSS_SHEET_FEEDS_GID: ${{ secrets.RSS_SHEET_FEEDS_GID }}
        run: Rscript newsletter_script.R