name: Daily Newsletter

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST
    - cron: '0 21 * * *'  # 4 PM EST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  # Correct indentation - steps should be under build
      - uses: actions/checkout@v3
      - uses: r-lib/setup-r@v2
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("httr2", "digest", "lubridate", "tidyRSS", "googlesheets4", "emayili", "markdown", "curl"))'

      - name: Cache GUIDs
        id: cache-guids
        uses: actions/cache@v3
        with:
          path: guids.csv
          key: ${{ runner.os }}-guids-${{ hashFiles('newsletter_script.R') }}
          restore-keys: |
            ${{ runner.os }}-guids-

      - name: Execute R Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RSS_SHEET_URL: ${{ secrets.RSS_SHEET_URL }}
          RSS_SHEET_NAME_SECTIONS: ${{ secrets.RSS_SHEET_NAME_SECTIONS || 'Sections' }}
          RSS_SHEET_NAME_FEEDS: ${{ secrets.RSS_SHEET_NAME_FEEDS || 'Feeds' }}
        run: Rscript ai_newsletter_script.R